### ISSUE TITLE
Only using normal ball, not using Great Ball/Ultra Ball when catch pokemon

### ISSUE THREAD

**Issue by thaihuyhung** [FeroxRev/Pokemon-Go-Rocket-API#121] opened 2016-07-21 06:40 UTC
Hi guys,

All the pokemon go away when there is no normal ball in my inventory.
I think it should use Great Balls, Ultra Balls, ...

Thanks for making this.

**Comment by jshield** [comment] 2016-07-21 06:43
Duplicate of #66

**Comment by Spegeli** [comment] 2016-07-21 06:52
A Pull Request is already open: https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/111

**Closed** 2016-07-21 10:17 UTC
