### ISSUE TITLE
Not working after (9a074d8)

### ISSUE THREAD

**Issue by chrisoro** [FeroxRev/Pokemon-Go-Rocket-API#89] opened 2016-08-01 20:22 UTC
Client.Map.GetMapObjects always returns a null reference
Client.Inventory.GetInventory() always returns a null reference

I haven't tried more but I guess every _client Task returns a null reference. Maybe problem with the newest POGOProtos? They changed some types again..

**Comment by Corlobin** [comment] 2016-08-01 20:36
That`s true. Here works just sometimes.
I think its caused by Niantic Update.

**Comment by chrisoro** [comment] 2016-08-01 20:46
I don't think its caused by Niantic because the e5ed64e revision is still working 100%

**Comment by raotskuhh** [comment] 2016-08-01 20:49
A fix for this would be nice !

**Comment by FeroxRev** [comment] 2016-08-01 21:00
This is because you have not set the ApiStrategy. I forced supplying an ApiStrategy when creating a Client in latest commit.

**Comment by Corlobin** [comment] 2016-08-01 21:13
Why are you using Task<ApiOperation> HandleApiFailure() ? This shouldn't be just ApiOperation HandleApiFailure()?

**Comment by FeroxRev** [comment] 2016-08-01 21:21
This allows async operations to also happen. If you only want to immediately return a value, just wrap it in a task.

**Closed as completed** 2016-08-01 21:54 UTC
